# Generated by Django 6.0.1 on 2026-02-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст биографии')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bio_images/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Биография',
                'verbose_name_plural': 'Биографии',
            },
        ),
    ]
